name: compilarion y pruebas c#
on: push
jobs:
  Compilacion:
    runs-on: ubuntu-latest
    environment: PRUEBAS
    steps:
      - run: echo "El secreto Google es ${{ secrets.GOOGLE_TOKEN }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dodnet-version: '5.1.x'
      - name: Instalamos dependencias de NET
        run: dotnet restore
      - name: compilamos
        run: dotnet build
      - name: ejecutamos las pruebas
        run: dotnet test
      - name: Publicar un release
        uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.github_TOKEN }}
        with:
          args: Nuevo Release
