name: compilarion y pruebas c#
on: push
jobs:
  Compilacion:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: compilamos
        run: dotnet build
      - name: ejecutamos las pruebas
        run: dotnet test
